version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      patch-updates:
        update-types: ["patch"]

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      patch-updates:
        update-types: ["patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch-updates:
        update-types: ["patch"]

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      patch-updates:
        update-types: ["patch"]

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      patch-updates:
        update-types: ["patch"]
