[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  include_ext = ["go", "sql"]
  exclude_dir = ["tmp", "vendor", "internal/storage/gen"]
  delay = 500

[log]
  time = true

[color]
  build = "yellow"
  runner = "green"
