ALTER TABLE tasks ADD COLUMN branch        TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN worktree_path TEXT NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN base_ref      TEXT NOT NULL DEFAULT '';
