/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks */
        get: {
            parameters: {
                query?: {
                    /** @description Case-insensitive substring search over title and description */
                    q?: string;
                    label?: string;
                    repo_id?: string;
                    type?: string;
                    git_state?: "pushed" | "pr_open" | "pr_merged" | "pr_closed";
                    /** @description When set, returns the direct children (subtasks) of this parent task (one family at a time), bypassing pagination. */
                    parent_id?: string;
                    /** @description Archived-task visibility. Omitted (default) hides archived tasks; "only" returns just archived tasks; "all" returns everything. */
                    archived?: "all" | "only";
                    /** @description Page size. Defaults to 200; values above 500 are clamped to 500. */
                    limit?: number;
                    /** @description Cursor for the next page: the id of the last task from the previous page (returned in that response's X-Next-Cursor header). Omit for the first page. */
                    after?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of tasks, newest first. When more tasks remain, the id to pass as the next `after` cursor is returned in the X-Next-Cursor header (absent on the final page). */
                200: {
                    headers: {
                        /** @description Cursor for the next page; absent when no more tasks remain. */
                        "X-Next-Cursor"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title: string;
                        description?: string;
                        type?: string;
                        repo_id: string;
                        workflow_id: string;
                    };
                };
            };
            responses: {
                /** @description Created task */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply one action to many tasks
         * @description Applies a single action to every task in ids. Each task is processed independently — one failure doesn't abort the rest. Returns 200 if every task succeeded, 207 if any failed; the per-task results array reports each outcome either way. "move" transitions are validated through the workflow engine exactly like PATCH /tasks/{id}/label.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ids: string[];
                        /** @enum {string} */
                        action: "move" | "pause" | "resume" | "archive" | "unarchive";
                        /** @description Required when action is move */
                        to_label?: string;
                        /** @description Optional transition note (move only) */
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description All tasks processed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results?: {
                                id?: string;
                                ok?: boolean;
                                error?: string;
                            }[];
                        };
                    };
                };
                /** @description Some tasks failed; see per-task results */
                207: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing ids */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a task */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a task */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a task's metadata */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title?: string;
                        description?: string;
                        type?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks/{id}/label": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Move task label (human-initiated) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        to_label: string;
                        note?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Invalid transition */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Gate required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/tasks/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Archive or unarchive a task
         * @description Archived tasks are hidden from the default board view, excluded from the GitHub PR status sweep, and never dispatched to agents. Archiving does not change the task's label.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        archived: boolean;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/tasks/{id}/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a task's dependency edges
         * @description Returns both directions of the task's dependency edges: the tasks it is blocked by (each with derived satisfaction state) and the tasks that depend on it. Dependencies are a pure dispatch gate — a task with any unsatisfied blocker is never picked up by the dispatcher, though a human can still move it anywhere.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskDependencies"];
                    };
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Add a dependency (this task depends on another)
         * @description Creates an edge so this task is not dispatched until the depended-on task reaches a terminal label or is archived. Both tasks must be in the same workflow, and the blocker's workflow must have a terminal label (otherwise the edge could never satisfy). Cycles and self-edges are rejected.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        depends_on_task_id: string;
                    };
                };
            };
            responses: {
                /** @description Dependency created */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Self-edge */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Edge already exists or would create a cycle */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/subtasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a subtask under a parent
         * @description Creates a child task under the parent named in the path (Mechanism 2). The create_subtask MCP tool posts here live during a planning run. The child inherits the parent's repo + workflow, lands on a human-gate (agent_ignore) label, and gets an auto-created parent→child dependency edge so the parent isn't dispatched until the child finishes. Guardrails: depth limit 1 (a subtask can't create subtasks), a per-parent cap (config max_subtasks, default 10), and — when a creating run is in flight — the run's config must have subtasks_enabled.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title: string;
                        description?: string;
                        /** @enum {string} */
                        type?: "feature" | "bug" | "chore" | "spike";
                        /** @description Optional landing label; must be an agent_ignore (human-gate) label. Defaults to the workflow's first agent_ignore label. */
                        label?: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Depth limit exceeded */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Creating run's config is not permitted to create subtasks */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Parent task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Per-parent subtask cap reached */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/dependencies/{dep_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a dependency edge */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    /** @description The depends_on_task_id of the edge to remove. */
                    dep_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dependency removed (idempotent) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve the current human gate */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        note?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject and push back with feedback */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        note?: string;
                        to_label?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update agent notes on a task */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Notes content (supports markdown) */
                        notes: string;
                        /** @description If true, append to existing notes */
                        append?: boolean;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks/{id}/review-comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List inline diff review comments on a task (open and resolved) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewComment"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add an inline diff review comment
         * @description Creates a persistent, file/line-anchored review comment on the task's diff. Open comments are injected into every subsequent agent run's prompt (under "OPEN REVIEW COMMENTS") until resolved — by the agent via the MCP resolve_comment tool, or by a human via PATCH.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        file_path: string;
                        /**
                         * @default new
                         * @enum {string}
                         */
                        side?: "old" | "new";
                        start_line: number;
                        end_line: number;
                        /** @description Diff content the comment anchors to */
                        quoted_text?: string;
                        /** @description The review comment text */
                        body: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewComment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/review-comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a review comment */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    comment_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Resolve or reopen a review comment */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    comment_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "resolved" | "open";
                        resolution_note?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewComment"];
                    };
                };
                /** @description Comment not found (or already resolved when resolving) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/tasks/{id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the task's branch diff against its base (this task's accumulated changes) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            branch?: string;
                            diff?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/pr-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build a pre-filled GitHub compare/PR URL for the task's branch
         * @description Returns a github.com/.../compare URL with the PR title and a markdown body (task description, agent notes, and commit subjects) pre-filled, so a human can open a fully-described PR in one click. Requires the repo to have a GitHub remote and the task to have a provisioned branch.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            url?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/pr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push the task's branch and open a GitHub pull request via the gh CLI
         * @description Pushes the task's branch to origin, then runs `gh pr create` with the title from the task and a body assembled from the description, agent notes, and commit subjects. The resulting PR URL and git state are stored on the task. Idempotent: if a PR already exists for the branch, that PR is returned instead of erroring. Requires the repo to have a GitHub remote, the task to have a provisioned branch, and the gh CLI to be authenticated.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            pr_url?: string;
                            /** @enum {string} */
                            git_state?: "" | "pushed" | "pr_open" | "pr_merged" | "pr_closed";
                        };
                    };
                };
                /** @description Task has no branch */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description gh pr create failed (e.g. not authenticated) */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agent runs for a task */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentRun"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an agent run */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentRun"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a running agent run
         * @description Signals an in-flight run to stop. The pool cancels the run's context — propagating to CLI subprocesses (exec.CommandContext) and aborting HTTP providers — then, once the provider returns, marks the run `cancelled` (not `failed`, and without consuming retry budget), pauses the task so it is not immediately re-dispatched, clears the active-run lock, and broadcasts `task.agent_done`. Cancellation is asynchronous: a 202 means it was signalled, not that the run has fully stopped.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancellation signalled. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example cancelling */
                            status?: string;
                            run_id?: string;
                        };
                    };
                };
                /** @description Run not found or does not belong to the task */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Run is not currently running (already finished or never started). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/runs/{run_id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reply to an agent waiting for human input
         * @description Answers a waiting_human run's request_human question with text and continues the work. Starts a new run that resumes the prior provider session where supported (claude provider, unless the agent config has resume_sessions off) so the reply lands as the next message of the same conversation; other providers start cold with the reply injected into the prompt ("RESPONSE FROM HUMAN"). The task stays on its current label — this is a conversation, not a workflow transition — and the replied-to run keeps its waiting_human status, matching the approve/reject flows. The reply is recorded at the top of the new run's log.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The human's answer to the agent's question. */
                        message: string;
                    };
                };
            };
            responses: {
                /** @description Reply dispatched; a new run was created. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The continuation run's id. */
                            run_id?: string;
                        };
                    };
                };
                /** @description Missing/empty message */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Run not found or does not belong to the task */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Run is not the task's active waiting_human run */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Worker pool is saturated */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/runs/{run_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a page of logs for an agent run
         * @description Returns a page of the run's log entries in chronological order (oldest first). Omit `before` to get the most recent page (the tail); pass a previous response's X-Prev-Cursor as `before` to load earlier entries.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page size. Defaults to 200; values above 1000 are clamped to 1000. */
                    limit?: number;
                    /** @description Cursor to load earlier entries: the id of the oldest entry the caller already has (returned in the previous response's X-Prev-Cursor header). Omit for the newest page. */
                    before?: string;
                };
                header?: never;
                path: {
                    id: string;
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of log entries, oldest first. When earlier entries remain, X-Has-More is "true" and X-Prev-Cursor carries the id to pass as the next `before` cursor. */
                200: {
                    headers: {
                        /** @description "true" when earlier entries exist before this page. */
                        "X-Has-More"?: string;
                        /** @description Cursor (id) to pass as the next `before` to load earlier entries. */
                        "X-Prev-Cursor"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentLog"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List task templates */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskTemplate"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a task template */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        title?: string;
                        description?: string;
                        /** @default feature */
                        type?: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskTemplate"];
                    };
                };
                /** @description A template with that name already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a task template */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskTemplate"];
                    };
                };
                /** @description Template not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update a task template */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        title?: string;
                        description?: string;
                        type?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskTemplate"];
                    };
                };
                /** @description Template not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description A template with that name already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a task template */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workflows */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workflow"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a workflow */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workflow"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a workflow with labels and transitions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workflow"];
                    };
                };
            };
        };
        /** Replace workflow labels and transitions */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workflow"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a workflow */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agent configs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentConfig"][];
                    };
                };
            };
        };
        put?: never;
        /** Create an agent config */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentConfig"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get an agent config */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentConfig"];
                    };
                };
            };
        };
        /** Update an agent config */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentConfig"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an agent config */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available models for a provider */
        get: {
            parameters: {
                query: {
                    provider: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Model list for the provider */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModelList"];
                    };
                };
                /** @description Missing provider parameter */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unknown provider */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/claude-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available Claude plugins and MCP servers for agent config selection
         * @description Claude-provider-specific. Discovers plugins from ~/.claude/plugins/installed_plugins.json and user-level MCP servers from ~/.claude.json's global mcpServers key on the server.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Discovered Claude plugins and MCP servers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaudeOptions"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List repos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Repo"][];
                    };
                };
            };
        };
        put?: never;
        /** Register a repo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Repo"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a repo */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Repo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Remove a repo */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{id}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get repo file tree */
        get: {
            parameters: {
                query?: {
                    ref?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ref?: string;
                            files?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard summary */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dashboard"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Provider / onboarding readiness checks
         * @description Reports the readiness of each agent provider and supporting piece of infrastructure so first-run misconfiguration is visible at a glance instead of surfacing as a failed agent run. Checks the claude CLI (present + authenticated), API keys for the anthropic/llm providers, qwen/opencode binaries (only for providers referenced by an enabled agent config), the MCP sidecar binary (MCP_SERVER_PATH), gh auth, and REPO_BASE_DIR. Checks are cheap and side-effect free (PATH lookups, credential/config-file existence, env/config values) — no real agent invocation is performed, so a green result means "ready as far as we can tell", not a live token validation.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ordered list of readiness checks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            checks?: components["schemas"]["ProviderCheck"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Task: {
            id?: string;
            title?: string;
            description?: string;
            /** @enum {string} */
            type?: "feature" | "bug" | "chore" | "spike";
            label?: string;
            repo_id?: string;
            workflow_id?: string;
            current_agent_run_id?: string | null;
            active_agent_run_id?: string | null;
            agent_notes?: string;
            /** @description Per-task git branch (empty until first dispatch) */
            branch?: string;
            /** @description Path to the task's git worktree */
            worktree_path?: string;
            /** @description Ref the branch forked from */
            base_ref?: string;
            /** @description If true, the task is never auto-picked-up by the dispatcher */
            paused?: boolean;
            /** @description If true, the task is hidden from the default board view (GET /tasks excludes it unless archived=all|only), skipped by the GitHub PR status sweep, and never picked up by the dispatcher. Independent of the task's label. */
            archived?: boolean;
            /** @enum {string} */
            git_state?: "" | "pushed" | "pr_open" | "pr_merged" | "pr_closed";
            /** @description URL of the GitHub pull request opened for this task's branch (via POST /tasks/{id}/pr, or discovered by the GitHub PR status sweep). Empty until a PR exists. */
            pr_url?: string;
            /** @description Number of consecutive automatic retries this task has had for transient provider errors (rate limits, network blips, upstream 5xx). Reset to 0 on a genuine failure or a successful run. */
            transient_retry_count?: number;
            /**
             * Format: date-time
             * @description If set, the task is in a backed-off auto-retry state and will not be picked up by the dispatcher again until this time.
             */
            next_retry_at?: string | null;
            /** @description Where the task was imported from ("github" for the GitHub Issues importer). Empty for manually created tasks. */
            source?: string;
            /** @description External item the task was imported from, unique within source (e.g. "owner/repo#123"). Empty for manually created tasks. */
            source_ref?: string;
            /** @description Derived (read-time) count of this task's dependency blockers whose edges are still unsatisfied. A task with any unsatisfied blocker is never picked up by the dispatcher. A blocker is satisfied once it reaches a terminal label or is archived. Zero when the task has no unsatisfied blockers. */
            blocked_by_count?: number;
            /** @description Derived (read-time) count of tasks that depend on this task (i.e. this task is a blocker for that many other tasks). */
            blocking_count?: number;
            /** @description Parent task id when this task is a subtask (Mechanism 2), else null. A subtask branches off its parent's branch and merges back on terminal; the parent isn't dispatched until every child finishes. */
            parent_task_id?: string | null;
            /** @description The agent run that created this subtask (provenance). */
            created_by_run_id?: string | null;
            /**
             * @description A subtask's branch merge-back state into its parent's branch. Empty for non-subtasks and until the child reaches a terminal label.
             * @enum {string}
             */
            merge_status?: "" | "pending" | "merged" | "merge_conflict";
            /** @description Derived: number of this task's direct children (0 if not a parent). */
            subtask_total?: number;
            /** @description Derived: children currently on a terminal label. */
            subtask_done?: number;
            /** @description Derived: children whose merge-back is in conflict. */
            subtask_conflicts?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @description One end of a task dependency edge (a blocker or a dependent). */
        DependencyEdge: {
            /** @description The other task in the edge */
            task_id?: string;
            title?: string;
            label?: string;
            archived?: boolean;
            /** @description For a blocker: whether the edge is satisfied (the blocker is terminal or archived). Not meaningful for dependents (always false there). */
            satisfied?: boolean;
        };
        /** @description Both directions of a task's dependency edges. */
        TaskDependencies: {
            /** @description Tasks this task depends on (its blockers), newest first. */
            blocked_by?: components["schemas"]["DependencyEdge"][];
            /** @description Tasks that depend on this task, newest first. */
            blocking?: components["schemas"]["DependencyEdge"][];
            /** @description Count of unsatisfied blockers */
            blocked_by_count?: number;
            /** @description Count of dependents */
            blocking_count?: number;
        };
        /** @description Reusable pre-filled title/description/type for recurring shapes of work (e.g. "upgrade dependency X", "fix flaky test"). Applied in the new-task form; creating a task from a template just pre-fills fields. */
        TaskTemplate: {
            id?: string;
            /** @description Unique display name */
            name?: string;
            title?: string;
            description?: string;
            /** @enum {string} */
            type?: "feature" | "bug" | "chore" | "spike";
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        WorkflowLabel: {
            id?: string;
            workflow_id?: string;
            name?: string;
            color?: string;
            sort_order?: number;
            agent_ignore?: number;
            is_terminal?: number;
        };
        WorkflowTransition: {
            id?: string;
            workflow_id?: string;
            from_label?: string;
            to_label?: string;
            /** @enum {string} */
            trigger_type?: "agent" | "human" | "both";
            agent_config_id?: string | null;
        };
        Workflow: {
            id?: string;
            name?: string;
            description?: string;
            labels?: components["schemas"]["WorkflowLabel"][];
            transitions?: components["schemas"]["WorkflowTransition"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AgentConfig: {
            id?: string;
            name?: string;
            /** @enum {string} */
            provider?: "claude_code" | "openai" | "anthropic" | "custom" | "opencode";
            model?: string;
            system_prompt?: string;
            /** @description JSON array of label names */
            labels?: string;
            /** @description JSON object of env vars */
            env?: string;
            max_tokens?: number;
            timeout_secs?: number;
            max_turns?: number;
            /** @description Number of automatic consecutive retries allowed for a task after a transient provider error (rate limit, network blip, upstream 5xx) before it is left failed / escalated to waiting_human for a human to intervene. 0 disables auto-retry. Default 3. */
            max_retries?: number;
            /** @description Base backoff, in seconds, before a transient-error retry becomes eligible for re-dispatch. Exponential backoff (base * 2^attempt, capped at 10 minutes) is applied on top of this base. Default 30. */
            retry_backoff_secs?: number;
            /** @description Whether new runs for a task resume the previous run's provider session (claude provider only; other providers ignore it). On by default. Off means every run starts cold — useful for stages that should look at the work with fresh eyes (e.g. agent review). */
            resume_sessions?: boolean;
            /** @description Whether this config's runs may decompose their task into subtasks via the create_subtask MCP tool (claude/qwen_code only). Off by default — a deliberate capability granted to a specific agent (the planner). */
            subtasks_enabled?: boolean;
            /** @description Per-parent cap on children this config may create. Default 10. */
            max_subtasks?: number;
            /** @description JSON array of Claude plugin IDs ("<name>@<marketplace>") enabled for this agent config. Claude-provider only; defaults to "[]" (all plugins off). */
            enabled_plugins?: string;
            /** @description JSON array of Claude user-level MCP server names (from ~/.claude.json's global mcpServers) enabled for this agent config. Claude-provider only; defaults to "[]" (all MCP servers off). */
            enabled_mcp_servers?: string;
            /** @description JSON array of shell-command glob patterns ("*" wildcard). If non-empty, only commands matching at least one pattern may run via run_bash/Bash. Fully enforced for anthropic, llm, and qwen_code. NOT an effective restriction for claude (the CLI only auto-approves matches; non-matching commands still run — see docs/providers/claude.md). Not enforced for opencode. Defaults to "[]" (no restriction). */
            command_allowlist?: string;
            /** @description JSON array of shell-command glob patterns ("*" wildcard). Commands matching any pattern here are always denied, regardless of command_allowlist. Checked first. Fully enforced for anthropic, llm, and claude. NOT enforced for qwen_code (no confirmed CLI denylist flag) or opencode. Defaults to "[]" (no restriction). */
            command_denylist?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ModelList: {
            provider?: string;
            default_model?: string;
            models?: string[];
        };
        /** @description Claude plugins and user-level MCP servers discovered on the server's Claude home directory (~/.claude/plugins/installed_plugins.json and the global mcpServers key in ~/.claude.json), for per-agent-config selection. */
        ClaudeOptions: {
            plugins?: {
                /** @description "<name>@<marketplace>" */
                id?: string;
                name?: string;
                marketplace?: string;
            }[];
            mcp_servers?: string[];
        };
        Repo: {
            id?: string;
            name?: string;
            path?: string;
            remote_url?: string | null;
            workflow_id?: string | null;
            /** @description 1 = open GitHub issues matching issue_sync_label are periodically imported as tasks (requires remote_url and workflow_id). 0 = off. */
            issue_sync_enabled?: number;
            /** @description Only import issues carrying this label (empty = all open issues). */
            issue_sync_label?: string;
            /**
             * @description State of the repo's initial auto-clone. 'ready' for local repos and finished clones; 'cloning' while an async git clone is in progress (POST /repos returns immediately with this status); 'error' if the clone failed (see clone_error). Watch the repo.clone_done / repo.clone_failed WebSocket events for transitions out of 'cloning'.
             * @enum {string}
             */
            clone_status?: "ready" | "cloning" | "error";
            /** @description Human-readable failure detail when clone_status is 'error'. */
            clone_error?: string;
            /** Format: date-time */
            created_at?: string;
        };
        /** @description A persistent, file/line-anchored inline review comment on a task's diff. Open comments are injected into every agent run's prompt until resolved (by an agent via the MCP resolve_comment tool, or by a human). */
        ReviewComment: {
            id?: string;
            task_id?: string;
            file_path?: string;
            /** @enum {string} */
            side?: "old" | "new";
            start_line?: number;
            end_line?: number;
            quoted_text?: string;
            body?: string;
            /** @enum {string} */
            status?: "open" | "resolved";
            resolution_note?: string | null;
            /** @description Run that resolved it; null when human-resolved */
            resolved_by_run_id?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AgentRun: {
            id?: string;
            task_id?: string;
            agent_config_id?: string;
            /** @enum {string} */
            status?: "pending" | "running" | "completed" | "failed" | "waiting_human" | "cancelled";
            feedback?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** @description Total input/prompt tokens consumed across the run (summed across all turns of a multi-turn agentic loop). 0 if the provider does not report usage (e.g. opencode currently). */
            input_tokens?: number;
            /** @description Total output/completion tokens consumed across the run. */
            output_tokens?: number;
            /**
             * Format: double
             * @description Estimated USD cost of the run. For the `claude` CLI provider this is the CLI's own authoritative total_cost_usd figure (which may legitimately be 0 under a Claude Max subscription); for anthropic/llm providers it is computed from input/output tokens via an internal, approximate pricing table. 0 if unknown/unreported.
             */
            cost_usd?: number;
            /** @description Provider-side conversation session recorded for this run (the claude/qwen CLI stream-json session_id). A later run on the same task under the same agent config resumes it (claude provider only, unless the config's resume_sessions is off). Empty for providers/runs without a session. */
            session_id?: string;
        };
        AgentLog: {
            id?: string;
            agent_run_id?: string;
            /** Format: date-time */
            timestamp?: string;
            /** @enum {string} */
            type?: "stdout" | "stderr" | "system" | "tool_call" | "tool_result";
            content?: string;
        };
        Dashboard: {
            label_counts?: {
                [key: string]: number;
            };
            active_agents?: {
                run_id?: string;
                task_id?: string;
                task_title?: string;
                agent_name?: string;
                started_at?: string;
            }[];
            intervention_queue?: {
                run_id?: string;
                task_id?: string;
                task_title?: string;
                message?: string | null;
                created_at?: string;
            }[];
            /** @description Aggregate token/cost usage across all runs in a terminal state (completed, failed, waiting_human). */
            cost_total?: {
                input_tokens?: number;
                output_tokens?: number;
                /** Format: double */
                cost_usd?: number;
            };
            /** @description Per-provider breakdown of token/cost usage, sorted by cost descending. Runs whose agent_config was later deleted are excluded (agent_config_id is set NULL on delete, so they can no longer be attributed to a provider). */
            cost_by_provider?: {
                provider?: string;
                input_tokens?: number;
                output_tokens?: number;
                /** Format: double */
                cost_usd?: number;
                run_count?: number;
            }[];
            /** @description Per-agent-config run analytics, sorted by run_count descending. Only runs in a terminal status (completed/failed/waiting_human) with a still-existing agent_config are included, same filtering as cost_by_provider. Two caveats: (1) avg_turns_to_done and the retry fields are attributed entirely to a task's *last* run's agent config, not proportionally split across every config a task passed through; (2) avg_transient_retries and tasks_with_retries are a live snapshot of tasks.transient_retry_count, which resets to 0 on success or escalation to a human — not a lifetime/historical retry count. */
            agent_config_stats?: {
                agent_config_id?: string;
                agent_name?: string;
                provider?: string;
                run_count?: number;
                completed_count?: number;
                failed_count?: number;
                waiting_human_count?: number;
                /** Format: double */
                success_rate_percent?: number;
                /** Format: double */
                avg_duration_secs?: number;
                /** Format: double */
                p90_duration_secs?: number;
                /** Format: double */
                avg_turns_to_done?: number;
                /** Format: double */
                avg_transient_retries?: number;
                tasks_with_retries?: number;
                input_tokens?: number;
                output_tokens?: number;
                /** Format: double */
                cost_usd?: number;
            }[];
            /** @description Live Claude account rate-limit usage from Anthropic's OAuth usage endpoint (5-hour rolling window + weekly window). `available` is false when the server has no Claude OAuth credentials or the fetch failed; other fields are zero/absent in that case. */
            claude_usage?: {
                available?: boolean;
                /** Format: double */
                five_hour_percent?: number;
                /** Format: date-time */
                five_hour_resets_at?: string | null;
                /** Format: double */
                weekly_percent?: number;
                /** Format: date-time */
                weekly_resets_at?: string | null;
            };
        };
        /** @description A single provider/onboarding readiness row. */
        ProviderCheck: {
            /** @description Stable identifier (e.g. claude_cli, mcp_sidecar, gh_auth). */
            id: string;
            /** @description Human-readable check name. */
            name: string;
            /**
             * @description ok = ready (green); warn = optional/degraded or heuristically undetected (yellow); error = required item missing, runs will fail (red).
             * @enum {string}
             */
            status: "ok" | "warn" | "error";
            /** @description One-line description of the current state. */
            detail: string;
            /** @description How to fix it; present when status is not ok. */
            hint?: string;
        };
        Error: {
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
